### PR TITLE
Tolerate a leading slash in the webpack chunk names

### LINKED ISSUE #11: [Bug] Public Path not being fully added
I've tried to add this to our webpack build script, however even if I use our full path with publicPath, it's not working since it resolves to the root url path. Let me explain:

Adding the plugin:

```js
new BugsnagSourceMapUploaderPlugin({
    apiKey: 'api-key-here',
    publicPath: 'http://example.com/some-path/',
    overwrite: true,
})
```

The files are uploaded successfully, however they have the `http://example.com/` base path, and not the full `http://example.com/some-path/`.

I've taken a quick look on the source code and seems to be here:

https://github.com/bugsnag/webpack-bugsnag-plugins/blob/b37fdd3657ba1286a3fffa1df4d899efca26b67a/source-map-uploader-plugin.js#L54-L58

Quickly testing on Node CLI:

```js
const url = require('url')

url.resolve('http://example.com/some-path/', '/main.js')
// 'http://example.com/main.js'

url.resolve('http://example.com/some-path/another-path/', '/main.js')
// 'http://example.com/main.js'

url.resolve('http://example.com/some-path/', 'main.js')
// 'http://example.com/some-path/main.js'

url.resolve('http://example.com/some-path/another-path/', 'main.js')
// 'http://example.com/some-path/another-path/main.js' 
```

It seems that the `source` variable have the `/` before the name. Perhaps removing the `/` before the file name or even adding a callback option as suggested on https://github.com/bugsnag/webpack-bugsnag-plugins/issues/8#issuecomment-385356627 may be an option.

By the way, we are using [laravel-mix](https://github.com/JeffreyWay/laravel-mix) as webpack wrapper.

### PR DESCRIPTION
**Pull request by bengourley**
Laravel mix sets webpack config in a way that results in chunk output paths having a leading slash. This causes the url resolve function to resolve from the url root, not relatively, as described in #11. This change strips a leading slash from the output path before resolving the url.

Fixes #11.

### CODE REVIEW

File: source-map-uploader-plugin.js [hunk 1]
```diff
@@ -54,7 +54,8 @@ class BugsnagSourceMapUploaderPlugin {
           url: resolve(
             // ensure publicPath has a trailing slash
             publicPath.replace(/[^/]$/, '$&/'),
-            source
+            // ensure source doesn't have a leading slash
```
Comment (martin308) [inline source-map-uploader-plugin.js]: it might be good to have this comment describe why this is being done, instead of what is being done

**Comment by bengourley** [comment]
> Should this be an option that you need to enable? 
No I think it is always what you want

> How does this affect things if it is passed an absolute url?

My understanding is that `source` is the "name" of the chunk relative to the output path, and so it is never absolute.
