### PR TITLE
fix: Handle missing source map asset

### LINKED ISSUE #18: TypeError: Cannot read property 'existsAt' of undefined
I'm trying to use this with the vue-cli 3.0 build.

vue.config.js
```js
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
const CompressionPlugin = require('compression-webpack-plugin');
const BrotliPlugin = require('brotli-webpack-plugin');
const { BugsnagSourceMapUploaderPlugin } = require('webpack-bugsnag-plugins');

module.exports = {
  configureWebpack: (config) => {
    if (process.env.NODE_ENV === 'production') {
      return {
        plugins: [
          new BugsnagSourceMapUploaderPlugin({
            apiKey: '<api key>',
            // appVersion: '1.0.0',
          }),
          new CompressionPlugin(),
          new BrotliPlugin(),
          new BundleAnalyzerPlugin({ analyzerMode: 'static' }),
        ],
      };
    }
    return {
      plugins: [
        new BundleAnalyzerPlugin({ openAnalyzer: false }),
      ],
    };
  },
  chainWebpack: (config) => {
    if (process.env.NODE_ENV === 'production') {
      return config.plugins.delete('fork-ts-checker');
    }
    return config;
  },
};

```

```
yarn run v1.9.4
$ vue-cli-service build

⠋  Building for production.../<vue project>/node_modules/webpack-bugsnag-plugins/source-map-uploader-plugin.js:54
            map: compilation.assets[map].existsAt,
                                         ^

TypeError: Cannot read property 'existsAt' of undefined
    at maps.map.map (/<vue project>/node_modules/webpack-bugsnag-plugins/source-map-uploader-plugin.js:54:42)
    at Array.map (<anonymous>)
    at chunkToSourceMapDescriptors (/<vue project>/node_modules/webpack-bugsnag-plugins/source-map-uploader-plugin.js:43:21)
    at Array.map (<anonymous>)
    at plugin (/<vue project>/node_modules/webpack-bugsnag-plugins/source-map-uploader-plugin.js:67:39)
    at _err0 (eval at create (/<vue project>/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at callback (/<vue project>/node_modules/copy-webpack-plugin/dist/index.js:126:17)
    at afterEmit (/<vue project>/node_modules/copy-webpack-plugin/dist/index.js:220:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/<vue project>/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/<vue project>/node_modules/tapable/lib/Hook.js:154:20)
    at asyncLib.forEach.err (/<vue project>/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:355:27)
    at done (/<vue project>/node_modules/neo-async/async.js:2854:11)
    at /<vue project>/node_modules/neo-async/async.js:2805:7
    at /<vue project>/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:141:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

### PR DESCRIPTION
**Pull request by bengourley**
Sometimes source maps exist in the chunk, but are not written to disk so do not appear in the compilation assets. This change checks for the existence of the asset before proceeding to use it.

Fixes #18

### CODE REVIEW

**Comment by bengourley** [comment]
Steps to reproduce/test the fix (I deemed this too unwieldy to add to the fixtures):

```sh
npx @vue/cli create a-room-with-a-vue
cd a room-with-a-vue
npm i webpack-bundle-analyzer compression-webpack-plugin brotli-webpack-plugin webpack-bugsnag-plugins
```

Create a `vue.config.js` in the root of the project with the following content:

```js
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
const CompressionPlugin = require('compression-webpack-plugin');
const BrotliPlugin = require('brotli-webpack-plugin');
const { BugsnagSourceMapUploaderPlugin } = require('webpack-bugsnag-plugins');

module.exports = {
  configureWebpack: (config) => {
    if (process.env.NODE_ENV === 'production') {
      return {
        plugins: [
          new BugsnagSourceMapUploaderPlugin({
            apiKey: '<api key>',
            // appVersion: '1.0.0',
          }),
          new CompressionPlugin(),
          new BrotliPlugin(),
          new BundleAnalyzerPlugin({ analyzerMode: 'static' }),
        ],
      };
    }
    return {
      plugins: [
        new BundleAnalyzerPlugin({ openAnalyzer: false }),
      ],
    };
  },
  chainWebpack: (config) => {
    if (process.env.NODE_ENV === 'production') {
      return config.plugins.delete('fork-ts-checker');
    }
    return config;
  },
};
```

You can substitute in an API key if you like, but it fails before that stage so it's not necessary to observe the problem.

To observe the problem run:

```
npm run build
```

Before this change, you should see an error like this:
```
⠼  Building for production.../Users/bengourley/Development/a-room-with-a-vue/node_modules/webpack-bugsnag-plugins/source-map-uploader-plugin.js:54
            map: compilation.assets[map].existsAt,
                                         ^

TypeError: Cannot read property 'existsAt' of undefined
```

Afterwards you should see it work and log a warning:

```
[BugsnagSourceMapUploaderPlugin] source map not found in compilation output "css/app.e2713bb0.css.map"
```

File: source-map-uploader-plugin.js [hunk 1]
```diff
@@ -44,8 +44,17 @@ class BugsnagSourceMapUploaderPlugin {
...
           const source = map ? chunk.files.find(file => file === map.replace('.map', '')) : null
 
-          if (!source || !map) {
-            console.warn(`${LOG_PREFIX} no source/map pair found for chunk "${chunk.id}"`)
+          if (!source) {
+            console.warn(`${LOG_PREFIX} no corresponding source found for "${map}" in chunk "${chunk.id}"`)
+            return null
+          }
+
+          if (!compilation.assets[source]) {
```
Comment (Cawllec) [inline source-map-uploader-plugin.js]: If this doesn't exist, it looks like it's still possible for `existsAt` to be called on it at line 62.  Will this cause another issue?

Comment (bengourley) [reply source-map-uploader-plugin.js]: Good catch, thanks! I'm missing a `return null` here.

File: source-map-uploader-plugin.js [hunk 2]
```diff
@@ -44,8 +44,18 @@ class BugsnagSourceMapUploaderPlugin {
           // for each *.map file, find a corresponding source file in the chunk
           const source = map ? chunk.files.find(file => file === map.replace('.map', '')) : null
 
-          if (!source || !map) {
-            console.warn(`${LOG_PREFIX} no source/map pair found for chunk "${chunk.id}"`)
+          if (!source) {
+            console.warn(`${LOG_PREFIX} no corresponding source found for "${map}" in chunk "${chunk.id}"`)
```
Comment (Cawllec) [inline source-map-uploader-plugin.js]: If `map` is not defined, `source` will be `null`, making this warning flag up.  Is there a way to make `map` here more descriptive for that case (rather than `undefined`?)

Comment (bengourley) [reply source-map-uploader-plugin.js]: `map` will always be defined, so I removed the ternary above too.
